Repository exesser/exess-skeleton, pull requests merged in 2021-06, with the labels that each got.

#12 Issue #11 Add issue templates, codeowners info and contribution guidelines
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/support-question.md
Labels: documentation

#19 Issue #4 - Add audit on CRUD.
  Makefile
  src/ExEss/Cms/CRUD/Config/records/1_flw_actions.json
  src/ExEss/Cms/CRUD/Config/records/2_grid_gridtemplates.json
  src/ExEss/Cms/CRUD/Config/records/5_list_external_object.json
  src/ExEss/Cms/CRUD/Config/records/8_list_dynamic_list.json
  src/ExEss/Cms/CRUD/Config/records/dash_dashboard.json
  src/ExEss/Cms/CRUD/Config/records/dash_dashboardproperties.json
  src/ExEss/Cms/CRUD/Config/records/dash_menuactions.json
  src/ExEss/Cms/CRUD/Config/records/list_cell.json
  src/ExEss/Cms/CRUD/Config/records/list_cells.json
  src/ExEss/Cms/CRUD/Config/records/list_row_action.json
  src/ExEss/Cms/CRUD/Config/records/menu_mainmenu.json
  src/ExEss/Cms/CRUD/Config/records/relation_dash_dashboardmenu_dash_menuactions_1.json
  src/ExEss/Cms/CRUD/Config/records/relation_dash_dashboardproperties.json
  src/ExEss/Cms/CRUD/Config/records/relation_menu_mainmenu_dash_dashboard_c.json
  src/ExEss/Cms/CRUD/Config/records/trans_translation.json
  src/ExEss/Cms/Service/DashboardService.php
Labels: enhancement

#23 Issue #16 - Remove BestOfferTool.
  assets/frontend/app/es6/best-offer/best-offer-accordion-wrapper/best-offer-accordion-wrapper.component.html
  assets/frontend/app/es6/best-offer/best-offer-accordion-wrapper/best-offer-accordion-wrapper.component.js
  assets/frontend/app/es6/best-offer/best-offer-accordion-wrapper/best-offer-accordion-wrapper.component.spec.js
  assets/frontend/app/es6/best-offer/best-offer-address/best-offer-address.component.html
  assets/frontend/app/es6/best-offer/best-offer-address/best-offer-address.component.js
  assets/frontend/app/es6/best-offer/best-offer-address/best-offer-address.component.spec.js
  assets/frontend/app/es6/best-offer/best-offer-datasource.factory.js
  assets/frontend/app/es6/best-offer/best-offer-datasource.factory.spec.js
  assets/frontend/app/es6/best-offer/best-offer.component.html
  assets/frontend/app/es6/best-offer/best-offer.component.js
  assets/frontend/app/es6/best-offer/best-offer.component.spec.js
  assets/frontend/app/languages/en_BE.json
  assets/frontend/app/languages/fr_BE.json
  assets/frontend/app/languages/nl_BE.json
  src/ExEss/Cms/Api/V8_Custom/Sidebar/AbstractBlueSidebar.php
  src/ExEss/Cms/Doctrine/Type/FlowFieldType.php
  tests/api/V8_Custom/Crud/resources/records_information/ExEss_Cms_Entity_FlowField.json
Labels: cleanup

#39 Issue #38 - Add code of conduct
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, enhancement
